const { initializeApp } = require("firebase-admin/app");
const { onCall, HttpsError } = require("firebase-functions/v2/https");
const { setGlobalOptions } = require("firebase-functions");
const logger = require("firebase-functions/logger");
const nodemailer = require("nodemailer");

initializeApp();
setGlobalOptions({ region: "us-central1" });

/**
 * EYECARE PREDICT: PREMIUM CLINICAL DISPATCH
 * High-Aesthetic, Professional Medical Template
 */
exports.sendDiagnosticEmail = onCall(async (request) => {
  if (!request.auth) {
    throw new HttpsError("unauthenticated", "Clinical authentication required.");
  }

  const { email, name, condition, confidence, attachment, fileName } = request.data;
  
  if (!email || !name) {
    throw new HttpsError("invalid-argument", "Incomplete patient metadata.");
  }

  try {
    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: "rswaroop5678@gmail.com",
        pass: "vybt hkrn kppi omvu"
      }
    });

    const mailOptions = {
      from: '"EyeCare Predict clinical" <rswaroop5678@gmail.com>',
      to: email,
      subject: `Diagnostic Assessment Insight: ${name}`,
      html: `
        <!DOCTYPE html>
        <html>
        <head>
          <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
            body { font-family: 'Inter', system-ui, -apple-system, sans-serif; background-color: #f4f7f9; margin: 0; padding: 40px 0; }
            .container { max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.05); }
            .header { background: #0f172a; padding: 40px; color: white; text-align: left; }
            .header img { height: 32px; margin-bottom: 20px; }
            .badge { background: #007aff; color: white; padding: 4px 12px; border-radius: 100px; font-size: 10px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; }
            .content { padding: 40px; color: #1e293b; line-height: 1.6; }
            .patient-name { font-size: 24px; font-weight: 700; margin-top: 10px; color: #0f172a; }
            .report-card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 24px; margin: 30px 0; border-left: 5px solid #007aff; }
            .label { font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }
            .result { font-size: 20px; font-weight: 700; color: #0f172a; margin: 0; }
            .footer { padding: 30px 40px; background: #f1f5f9; color: #94a3b8; font-size: 12px; text-align: center; }
            .signature { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; font-size: 14px; color: #475569; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <span class="badge">Verified Diagnostic Report</span>
              <h1 style="margin: 20px 0 0; font-size: 22px; letter-spacing: -0.5px;">EyeCare Predict Analysis</h1>
            </div>
            <div class="content">
              <p style="margin: 0; color: #64748b; font-weight: 600;">Dear Patient,</p>
              <div class="patient-name">${name}</div>
              
              <p style="margin-top: 25px;">Your digital ophthalmic diagnostic summary has been successfully generated. We have performed an automated AI analysis on your recent fundus photography scan.</p>
              
              <div class="report-card">
                <div class="label">Primary Clinical Insight</div>
                <div class="result">${condition}</div>
                <div style="margin-top: 15px;">
                  <span style="font-size: 12px; color: #64748b;">AI Detection Confidence: </span>
                  <span style="font-size: 13px; font-weight: 700; color: #007aff;">${Math.round(confidence * 100)}%</span>
                </div>
              </div>
              
              <p style="font-size: 14px; color: #475569;">Please review the <strong>attached formal PDF report</strong> for comprehensive score breakdown, SVM corroboration, and specialist clinical notes.</p>
              
              <div class="signature">
                <strong>The EyeCare Predict Clinical Team</strong><br>
                Advanced Retinal Analysis Unit
              </div>
            </div>
            <div class="footer">
              <p>This is a confidential medical summary generated by EyeCare Predict AI. This report does not replace a clinical examination by a qualified ophthalmologist.</p>
              <p>© 2026 EyeCare Predict Inc. | Secured by Medical Grade Encryption</p>
            </div>
          </div>
        </body>
        </html>
      `,
      attachments: attachment ? [{
        filename: fileName || 'EyeCare_Clinical_Report.pdf',
        content: attachment,
        encoding: 'base64'
      }] : []
    };

    await transporter.sendMail(mailOptions);
    return { success: true, message: "Premium Clinical Dispatch Successful." };

  } catch (error) {
    logger.error("Premium SMTP Delivery Error:", error);
    throw new HttpsError("internal", error.message);
  }
});
