import React, { useEffect, useMemo, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import Sidebar from "../pages/Sidebar";
import Header from "../pages/Header";
import { db, auth, functions } from "../firebase";
import { useTheme } from "../context/ThemeContext";
import { httpsCallable } from "firebase/functions";
import { doc, onSnapshot, collection, query, where, getDocs, updateDoc } from "firebase/firestore";

export default function PatientProfile() {
  const { patientId } = useParams();
  const navigate = useNavigate();
  const { isDarkMode } = useTheme();

  const [patient, setPatient] = useState(null);
  const [reports, setReports] = useState([]);
  const [doctorId, setDoctorId] = useState(null);

  // EDITING STATES
  const [isEditing, setIsEditing] = useState(false);
  const [editForm, setEditForm] = useState({});
  const [isSaving, setIsSaving] = useState(false);

  /* ---------------- PDF GENERATION HELPER ---------------- */
  const generateMedicalReport = async (latestReport) => {
    if (!latestReport || !patient) return null;
    const { default: jsPDF } = await import('jspdf');
    await import('jspdf-autotable');

    const doc = new jsPDF();
    const primaryColor = [0, 122, 255]; 

    doc.setFillColor(15, 23, 42); 
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("EyeDisease Predict", 15, 25);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Clinical Diagnostic Summary Report", 15, 32);

    const diagnosticDate = latestReport.createdAt?.toDate ? latestReport.createdAt.toDate() : new Date(latestReport.createdAt || Date.now());
    const formattedDateTime = `${diagnosticDate.toLocaleDateString()} ${diagnosticDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;

    doc.autoTable({
      startY: 50,
      head: [['Field', 'Patient Details']],
      body: [
        ['Patient Name', patient.name || 'N/A'],
        ['Patient ID', patient.patientId || 'N/A'],
        ['Age / Gender', `${patient.age || 'N/A'} Yrs / ${patient.gender || 'N/A'}`],
        ['Blood Type', patient.bloodtype || 'N/A'],
        ['Diagnostic Date & Time', formattedDateTime]
      ],
      headStyles: { fillColor: primaryColor },
      theme: 'striped'
    });

    const lastY = doc.previousAutoTable.finalY + 15;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Automated AI Analysis Results", 15, lastY);

    const cnnTop = latestReport.cnn_top5?.[0];
    const svmTop = latestReport.svm_top5?.[0];
    const finalLabel = latestReport.prediction || "N/A";

    doc.autoTable({
      startY: lastY + 5,
      head: [['Engine', 'Likely Condition', 'Confidence']],
      body: [
        ['CNN Model', cnnTop?.label || finalLabel, `${Math.round((cnnTop?.confidence || latestReport.confidence || 0.80) * 100)}%`],
        ['SVM Model', svmTop?.label || latestReport.svm_prediction || finalLabel, `${Math.round((svmTop?.confidence || latestReport.svm_confidence || latestReport.confidence || 0.82) * 100)}%`]
      ],
      headStyles: { fillColor: [52, 211, 153] },
    });

    const noteY = doc.previousAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.text("Professional Ophthalmological Feedback", 15, noteY);
    doc.setFontSize(10);
    doc.setFont("helvetica", "italic");
    const notes = latestReport.doctorNotes || "No specific feedback provided for this scan.";
    doc.text(doc.splitTextToSize(`"${notes}"`, 180), 15, noteY + 10);

    const sigY = noteY + 50;
    doc.line(140, sigY, 195, sigY);
    doc.setFont("helvetica", "normal");
    doc.text("Authorized Signature", 140, sigY + 5);

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Report generated by EyeDisease Predict System • ID: ${latestReport.id}`, 15, 285);

    return doc;
  };

  /* ---------------- LOAD DOCTOR ID (For Notifications) ---------------- */
  useEffect(() => {
    const fetchDoctorId = async () => {
      const user = auth.currentUser;
      if (!user) return;

      try {
        const q = query(
          collection(db, "doctors"),
          where("email", "==", user.email)
        );
        const snapshot = await getDocs(q);

        if (!snapshot.empty) {
          const docData = snapshot.docs[0].data();
          setDoctorId(docData.employeeId || snapshot.docs[0].id);
        }
      } catch (err) {
        console.error("Error fetching doctor ID:", err);
      }
    };
    fetchDoctorId();
  }, []);

  /* ---------------- REAL-TIME PATIENT SYNC ---------------- */
  useEffect(() => {
    if (!patientId) return;

    const unsubscribe = onSnapshot(doc(db, "patients", patientId), (snap) => {
      if (snap.exists()) {
        const data = snap.data();
        setPatient(data);
      }
    });

    return () => unsubscribe();
  }, [patientId]);

  /* ---------------- LOAD REPORTS (PREDICTIONS) ---------------- */
  useEffect(() => {
    if (patient?.reports && Array.isArray(patient.reports)) {
      setReports(patient.reports);
    } else {
      setReports([]);
    }
  }, [patient]);

  /* ---------------- DERIVED DATA ---------------- */

  const sortedReports = useMemo(() => {
    return [...reports].sort((a, b) => {
      const t1 = a.createdAt?.seconds
        ? a.createdAt.seconds * 1000
        : new Date(a.createdAt || 0).getTime();
      const t2 = b.createdAt?.seconds
        ? b.createdAt.seconds * 1000
        : new Date(b.createdAt || 0).getTime();
      return t2 - t1;
    });
  }, [reports]);

  const handleEditToggle = () => {
    if (!isEditing) {
      setEditForm({
        name: patient.name || "",
        age: patient.age || "",
        gender: patient.gender || "",
        bloodtype: patient.bloodtype || "",
        email: patient.email || "",
        Phno: patient.Phno || "",
        medicalHistory: patient.medicalHistory || "",
        lastVisit: patient.lastVisit || "",
      });
    }
    setIsEditing(!isEditing);
  };

  const handleSave = async () => {
    setIsSaving(true);
    try {
      const ref = doc(db, "patients", patientId);
      await updateDoc(ref, editForm);
      setIsEditing(false);
    } catch (err) {
      console.error("Save failed:", err);
      alert("Failed to update patient details.");
    } finally {
      setIsSaving(false);
    }
  };

  if (!patient) {
    return (
      <div
        className={`min-h-screen flex items-center justify-center ${isDarkMode ? "text-white" : "text-gray-900"
          }`}
      >
        Loading patient profile…
      </div>
    );
  }

  return (
    <div
      className={`flex min-h-screen font-sans transition-colors duration-300 ${isDarkMode ? "bg-[#0f172a] text-white" : "bg-gray-50 text-gray-900"
        }`}
    >
      <Sidebar />

      <div className="flex-1 flex flex-col">
        <Header doctorId={doctorId} />

        <main className="p-8 max-w-6xl mx-auto w-full space-y-8">
          <div className="flex flex-col md:flex-row justify-between items-center gap-4">
            <div
              className={`text-sm flex items-center gap-2 ${isDarkMode ? "text-muted-dark" : "text-gray-500"
                }`}
            >
              <button
                onClick={() => navigate("/patients")}
                className={`transition-colors ${isDarkMode ? "hover:text-white" : "hover:text-gray-900"
                  }`}
              >
                Patients
              </button>
              <span>›</span>
              <span
                className={`font-medium ${isDarkMode ? "text-white" : "text-gray-900"
                  }`}
              >
                Patient Profile
              </span>
            </div>

            <div className="flex gap-3">
              <button 
                onClick={async () => {
                  const doc = await generateMedicalReport(sortedReports[0]);
                  if (doc) doc.save(`${patient.name.replace(/\s+/g, '_')}_Clinical_Report.pdf`);
                }}
                className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm font-medium rounded-lg transition-colors shadow-sm active:scale-95"
              >
                <span className="material-symbols-outlined text-[18px]">download</span>
                Download Report
              </button>

              <button 
                onClick={async () => {
                  try {
                    const latest = sortedReports[0];
                    if (!latest) {
                      alert("No diagnostic reports found.");
                      return;
                    }

                    // 📄 Generate Attachment
                    const reportDoc = await generateMedicalReport(latest);
                    const pdfBase64 = reportDoc.output('datauristring').split(',')[1];

                    const sendReport = httpsCallable(functions, "sendDiagnosticEmail");
                    const result = await sendReport({
                      email: patient.email,
                      name: patient.name,
                      condition: latest.prediction || "Unknown",
                      confidence: latest.confidence || 0.85,
                      reportId: latest.id,
                      attachment: pdfBase64,
                      fileName: `${patient.name.replace(/\s+/g, '_')}_EyeCare_Report.pdf`
                    });

                    if (result.data?.success) {
                      alert(`✨ Report dispatched successfully to ${patient.email}`);
                    } else {
                      alert(`Backend Error: ${result.data?.error || "Unknown error during delivery"}`);
                    }
                  } catch (err) {
                    console.error("Cloud Function Error:", err);
                    alert(`Delivery Failed: ${err.message}\n\n(Tip: Ensure you are logged in and the server is updated.)`);
                  }
                }}
                className="flex items-center gap-2 px-4 py-2 bg-[#007aff] hover:bg-[#0062cc] text-white text-sm font-medium rounded-lg transition-colors shadow-sm active:scale-95"
              >
                <span className="material-symbols-outlined text-[18px]">send</span>
                Send to Patient
              </button>
            </div>
          </div>

          <div
            className={`rounded-[2rem] p-10 border transition-all duration-700 relative overflow-hidden ${
              isDarkMode
                ? "bg-gradient-to-br from-[#111a22] to-[#0d141b] border-white/5 shadow-[0_32px_64px_-16px_rgba(0,0,0,0.4)]"
                : "bg-white border-slate-200/60 shadow-[0_32px_64px_-16px_rgba(15,23,42,0.08)]"
              }`}
          >
            {/* AMBIENT DECOR */}
            {isDarkMode && <div className="absolute top-0 right-0 w-64 h-64 bg-[#007aff]/5 blur-[100px] pointer-events-none" />}

            <div className={`flex items-center justify-between mb-10 pb-6 border-b ${isDarkMode ? 'border-white/5' : 'border-slate-100'}`}>
              <div className="flex flex-col gap-1">
                 <div className="flex items-center gap-2">
                    <div className="w-2 h-2 rounded-full bg-[#007aff] animate-pulse" />
                    <h2 className={`text-base font-black uppercase tracking-[0.2em] ${isDarkMode ? "text-slate-400" : "text-slate-500"}`}>
                      Clinical Identity Registry
                    </h2>
                 </div>
                 <p className={`text-xs ${isDarkMode ? 'text-slate-500' : 'text-slate-400'}`}>Authenticated Specialist Access Only</p>
              </div>
              <div className="flex gap-3">
                {isEditing && (
                  <button 
                    onClick={() => setIsEditing(false)}
                    disabled={isSaving}
                    className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-xs font-black uppercase tracking-widest transition-all active:scale-95 border ${
                      isDarkMode 
                      ? "border-red-500/30 text-red-400 hover:bg-red-500/10" 
                      : "border-red-200 text-red-600 hover:bg-red-50"
                    }`}
                  >
                    <span className="material-symbols-outlined text-[16px]">close</span>
                    Cancel
                  </button>
                )}
                <button 
                  onClick={isEditing ? handleSave : handleEditToggle}
                  disabled={isSaving}
                  className={`flex items-center gap-2 px-4 py-1.5 rounded-lg text-xs font-black uppercase tracking-widest transition-all active:scale-95 ${
                    isEditing 
                    ? "bg-emerald-500 text-white shadow-[0_0_15px_rgba(16,185,129,0.3)]"
                    : "bg-[#007aff]/10 text-[#007aff] border border-[#007aff]/30 hover:bg-[#007aff]/20"
                  }`}
                >
                  <span className="material-symbols-outlined text-[16px]">
                    {isSaving ? "progress_activity" : (isEditing ? "save" : "edit")}
                  </span>
                  {isSaving ? "Saving..." : (isEditing ? "Save Changes" : "Edit Profile")}
                </button>
              </div>
            </div>

            <div className="flex flex-col lg:flex-row gap-12 items-start relative z-10">
              <div className="shrink-0 relative group">
                <img
                  src={patient.photoUrl || "/avatar.png"}
                  className={`w-40 h-40 rounded-[2.5rem] object-cover border-4 transition-transform duration-500 group-hover:scale-105 shadow-2xl ${
                    isDarkMode ? "border-white/5 shadow-black/40" : "border-white shadow-slate-200"
                  }`}
                  alt="patient"
                />
                <div className={`absolute -bottom-2 -right-2 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-widest border-2 ${
                  isDarkMode ? 'bg-[#111a22] border-[#233648] text-primary' : 'bg-white border-slate-100 text-primary'
                }`}>
                  Internal Case
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-x-24 gap-y-10 flex-1 w-full pt-2">
                <div className="space-y-4">
                  <div className="space-y-1">
                    {isEditing ? (
                      <div className="relative group max-w-sm">
                        <input 
                          type="text"
                          value={editForm.name}
                          onChange={(e) => setEditForm({...editForm, name: e.target.value})}
                          placeholder="Legal Name"
                          className={`text-2xl font-black tracking-tight px-5 py-3 rounded-2xl border outline-none w-full transition-all duration-300 ${isDarkMode ? "bg-[#0d141b] border-white/5 text-white focus:border-[#007aff]/50 focus:ring-4 focus:ring-[#007aff]/10" : "bg-slate-50 border-slate-200 text-slate-900 focus:border-primary/50 focus:ring-4 focus:ring-primary/5 shadow-sm"}`}
                        />
                        <div className="absolute -top-3 left-6 bg-[#0c141d] px-3 text-[9px] font-black uppercase tracking-[0.2em] text-[#007aff] z-10 whitespace-nowrap shadow-sm rounded-full border border-white/5">
                          Patient Descriptor
                        </div>
                      </div>
                    ) : (
                      <h1
                        className={`text-4xl font-black tracking-tighter ${isDarkMode ? "text-white" : "text-slate-900"
                          }`}
                      >
                        {patient.name}
                      </h1>
                    )}
                    <div className="flex items-center gap-3">
                      <p className="text-[#007aff] font-mono text-xs font-bold bg-[#007aff]/10 px-2.5 py-1 rounded-lg border border-[#007aff]/20 uppercase tracking-widest">
                        Registry: {patient.patientId}
                      </p>
                    </div>
                  </div>

                  <div className={`grid gap-x-12 gap-y-10 pt-4 ${isEditing ? "grid-cols-1" : "grid-cols-1 sm:grid-cols-2"}`}>
                    <div className="group/field">
                      <p
                        className={`text-[10px] uppercase tracking-[0.2em] font-black mb-2 transition-colors ${isDarkMode ? "text-slate-500 group-hover/field:text-primary" : "text-slate-400"
                          }`}
                      >
                        Patient Age
                      </p>
                      {isEditing ? (
                        <div className="relative flex items-center max-w-[200px]">
                          <input 
                            type="number"
                            value={editForm.age}
                            onChange={(e) => setEditForm(prev => ({...prev, age: e.target.value}))}
                            className={`text-lg font-black pl-5 pr-16 py-3 rounded-2xl border outline-none w-full transition-all duration-300 [appearance:textfield] [&::-webkit-outer-spin-button]:appearance-none [&::-webkit-inner-spin-button]:appearance-none ${isDarkMode ? "bg-[#0d141b] border-white/5 text-white focus:border-[#007aff]/50 focus:ring-4 focus:ring-[#007aff]/10" : "bg-slate-50 border-slate-200 text-slate-900 focus:border-primary/50 focus:ring-4 focus:ring-primary/10"}`}
                          />
                          <div className="absolute right-10 flex flex-col -gap-1 z-30">
                             <button 
                               type="button"
                               onClick={() => setEditForm(prev => ({...prev, age: (parseInt(prev.age) || 0) + 1}))}
                               className="hover:text-primary transition-colors active:scale-125"
                             >
                               <span className="material-symbols-outlined text-[18px] leading-[10px]">expand_less</span>
                             </button>
                             <button 
                               type="button"
                               onClick={() => setEditForm(prev => ({...prev, age: Math.max(0, (parseInt(prev.age) || 0) - 1)}))}
                               className="hover:text-primary transition-colors active:scale-125"
                             >
                               <span className="material-symbols-outlined text-[18px] leading-[10px]">expand_more</span>
                             </button>
                          </div>
                          <span className="absolute right-4 top-1/2 -translate-y-1/2 pointer-events-none opacity-30 text-[10px] font-black uppercase tracking-tighter">YRS</span>
                        </div>
                      ) : (
                        <div className="flex items-baseline gap-1.5 transition-transform group-hover/field:translate-x-1">
                          <p className={`text-2xl font-black tracking-tight ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>{patient.age || "—"}</p>
                          <span className="text-[10px] font-black uppercase tracking-widest opacity-30">Years</span>
                        </div>
                      )}
                    </div>
                    <div className="group/field">
                      <p className={`text-[10px] uppercase tracking-[0.2em] font-black mb-2 transition-colors ${isDarkMode ? "text-slate-500 group-hover/field:text-primary" : "text-slate-400"}`}>
                        Gender Identity
                      </p>
                      {isEditing ? (
                        <div className="relative w-full max-w-[280px]">
                          <select 
                            value={editForm.gender}
                            onChange={(e) => setEditForm(prev => ({...prev, gender: e.target.value}))}
                            className={`appearance-none bg-none text-lg font-black tracking-tight rounded-2xl px-5 py-4 pr-12 outline-none border w-full transition-all duration-300 cursor-pointer select-none [&::-ms-expand]:hidden [-webkit-appearance:none] [-moz-appearance:none] [appearance:none] ${isDarkMode ? "bg-[#0d141b] border-white/5 text-white focus:border-[#007aff]/50 focus:ring-4 focus:ring-[#007aff]/10" : "bg-slate-50 border-slate-200 text-slate-900 shadow-sm"}`}
                          >
                            <option value="Male">Male</option>
                            <option value="Female">Female</option>
                            <option value="Other">Other</option>
                          </select>
                          <div className="absolute right-4 top-0 bottom-0 flex items-center justify-center pointer-events-none opacity-40">
                             <span className="material-symbols-outlined text-[20px]">keyboard_arrow_down</span>
                          </div>
                        </div>
                      ) : (
                        <p className={`text-2xl font-black tracking-tight capitalize transition-all group-hover/field:translate-x-1 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>
                          {patient.gender || "—"}
                        </p>
                      )}
                    </div>
                    <div className="group/field">
                      <p className={`text-[10px] uppercase tracking-[0.2em] font-black mb-2 transition-colors ${isDarkMode ? "text-slate-500 group-hover/field:text-primary" : "text-slate-400"}`}>
                        Clinical Blood Type
                      </p>
                      {isEditing ? (
                        <div className="relative w-full max-w-[280px]">
                          <select 
                            value={editForm.bloodtype}
                            onChange={(e) => setEditForm(prev => ({...prev, bloodtype: e.target.value}))}
                            className={`appearance-none bg-none text-lg font-black tracking-tight rounded-2xl px-5 py-4 pr-12 outline-none border w-full transition-all duration-300 cursor-pointer select-none [&::-ms-expand]:hidden [-webkit-appearance:none] [-moz-appearance:none] [appearance:none] ${isDarkMode ? "bg-[#0d141b] border-white/5 text-white focus:border-[#007aff]/50 focus:ring-4 focus:ring-[#007aff]/10" : "bg-slate-50 border-slate-200 text-slate-900 shadow-sm"}`}
                          >
                            <option value="">—</option>
                            {["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"].map(bt => (
                              <option key={bt} value={bt}>{bt}</option>
                            ))}
                          </select>
                          <div className="absolute right-4 top-0 bottom-0 flex items-center justify-center pointer-events-none opacity-40">
                             <span className="material-symbols-outlined text-[20px]">keyboard_arrow_down</span>
                          </div>
                        </div>
                      ) : (
                        <p className={`text-2xl font-black tracking-tight transition-all group-hover/field:translate-x-1 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>
                          {patient.bloodtype || "—"}
                        </p>
                      )}
                    </div>
                    <div className="group/field">
                      <p className={`text-[10px] uppercase tracking-[0.2em] font-black mb-2 transition-colors ${isDarkMode ? "text-slate-500 group-hover/field:text-primary" : "text-slate-400"}`}>
                        Official Last Entry
                      </p>
                      {isEditing ? (
                        <div className="relative w-full">
                          <input 
                            type="date"
                            value={editForm.lastVisit ? new Date(editForm.lastVisit).toISOString().split('T')[0] : ""}
                            onChange={(e) => setEditForm(prev => ({...prev, lastVisit: e.target.value}))}
                            className={`text-xs font-black px-5 py-3 rounded-2xl border outline-none w-full transition-all duration-300 cursor-pointer ${isDarkMode ? "bg-[#0d141b] border-white/5 text-white focus:border-[#007aff]/50 focus:ring-4 focus:ring-[#007aff]/10" : "bg-slate-50 border-slate-200 text-slate-900 shadow-sm"}`}
                          />
                        </div>
                      ) : (
                        <p className={`text-2xl font-black tracking-tight transition-all group-hover/field:translate-x-1 ${isDarkMode ? 'text-white' : 'text-slate-900'}`}>
                          {patient.lastVisit
                            ? new Date(patient.lastVisit).toLocaleDateString(
                              "en-US",
                              {
                                year: "numeric",
                                month: "short",
                                day: "numeric",
                              }
                            )
                            : "—"}
                        </p>
                      )}
                    </div>
                  </div>

                </div>

                <div className="space-y-6 pt-2">
                  <p
                    className={`text-[10px] uppercase tracking-[0.2em] font-black ${isDarkMode ? "text-slate-500" : "text-slate-400"
                      }`}
                  >
                    Clinical Contact Details
                  </p>
                  <div className="space-y-4">
                    <div
                      className={`flex items-center gap-4 text-sm group/contact ${isDarkMode ? "text-slate-300" : "text-slate-600"
                        }`}
                    >
                      <div
                        className={`w-12 h-12 rounded-full flex-none flex items-center justify-center border transition-all duration-300 group-hover/contact:scale-110 ${isDarkMode
                          ? "bg-white/5 border-white/5 text-slate-400 group-hover/contact:text-[#007aff] group-hover/contact:border-[#007aff]/30"
                          : "bg-slate-50 border-slate-200 text-slate-400 group-hover/contact:text-[#007aff] group-hover/contact:border-primary/30"
                          }`}
                      >
                        <span className="material-symbols-outlined text-[22px]">mail</span>
                      </div>
                      <div className="flex flex-col">
                        <span className="text-[10px] font-black uppercase opacity-30">Registered Email</span>
                        {isEditing ? (
                          <input 
                            type="email"
                            value={editForm.email}
                            onChange={(e) => setEditForm(prev => ({...prev, email: e.target.value}))}
                            className={`px-4 py-2.5 rounded-2xl border outline-none text-xs font-bold transition-all duration-300 ${isDarkMode ? "bg-[#0d141b] border-white/5 text-white focus:border-[#007aff]/50 focus:ring-4 focus:ring-[#007aff]/10" : "bg-slate-50 border-slate-200 text-slate-900 shadow-sm"}`}
                          />
                        ) : (
                          <span className="font-bold tracking-tight">{patient.email || "—"}</span>
                        )}
                      </div>
                    </div>

                    <div
                      className={`flex items-center gap-4 text-sm group/contact ${isDarkMode ? "text-slate-300" : "text-slate-600"
                        }`}
                    >
                      <div
                        className={`w-12 h-12 rounded-full flex-none flex items-center justify-center border transition-all duration-300 group-hover/contact:scale-110 ${isDarkMode
                          ? "bg-white/5 border-white/5 text-slate-400 group-hover/contact:text-[#007aff] group-hover/contact:border-[#007aff]/30"
                          : "bg-slate-50 border-slate-200 text-slate-400 group-hover/contact:text-[#007aff] group-hover/contact:border-primary/30"
                          }`}
                      >
                        <span className="material-symbols-outlined text-[22px]">call</span>
                      </div>
                      <div className="flex flex-col">
                        <span className="text-[10px] font-black uppercase opacity-30">Primary Contact</span>
                        {isEditing ? (
                          <input 
                            type="text"
                            value={editForm.Phno}
                            onChange={(e) => setEditForm(prev => ({...prev, Phno: e.target.value}))}
                            className={`px-4 py-2.5 rounded-2xl border outline-none text-xs font-bold transition-all duration-300 ${isDarkMode ? "bg-[#0d141b] border-white/5 text-white focus:border-[#007aff]/50 focus:ring-4 focus:ring-[#007aff]/10" : "bg-slate-50 border-slate-200 text-slate-900 shadow-sm"}`}
                          />
                        ) : (
                          <span className="font-bold tracking-tight">{patient.Phno || "—"}</span>
                        )}
                      </div>
                    </div>
                  </div>
                </div>

                <div className="pt-2 xl:pl-12">
                  <p
                    className={`text-[10px] uppercase tracking-[0.2em] font-black mb-4 ${isDarkMode ? "text-slate-500" : "text-slate-400"
                      }`}
                  >
                    Historical Medical Record
                  </p>

                  {isEditing ? (
                    <div className="relative group">
                      <textarea 
                        value={editForm.medicalHistory}
                        onChange={(e) => setEditForm(prev => ({...prev, medicalHistory: e.target.value}))}
                        placeholder="Clinical conditions (comma separated)..."
                        className={`w-full h-32 p-5 rounded-[1.5rem] border text-sm font-bold focus:outline-none transition-all duration-500 ${
                          isDarkMode 
                          ? "bg-[#0d141b] border-white/5 text-white focus:border-[#007aff]/50 focus:ring-4 focus:ring-[#007aff]/10" 
                          : "bg-slate-50 border-slate-200 text-slate-900 focus:border-primary/50 focus:ring-4 focus:ring-primary/5"
                        }`}
                      />
                      <div className="absolute top-4 right-4 pointer-events-none opacity-20">
                         <span className="material-symbols-outlined">history_edu</span>
                      </div>
                    </div>
                  ) : (
                    <div className="relative">
                      {patient.medicalHistory ? (
                        <div className="flex flex-wrap gap-2.5">
                          {patient.medicalHistory.split(",").map((item, i) => (
                            <div
                              key={i}
                              className={`px-4 py-2 border rounded-xl text-[10px] font-black uppercase tracking-widest transition-all hover:scale-105 ${isDarkMode
                                ? "bg-white/[0.03] border-white/5 text-slate-300"
                                : "bg-slate-50 border-slate-200 text-slate-600"
                                }`}
                            >
                              {item.trim()}
                            </div>
                          ))}
                        </div>
                      ) : (
                        <div className={`p-6 rounded-2xl border border-dashed flex flex-col items-center justify-center gap-2 ${isDarkMode ? 'border-white/10 text-slate-600' : 'border-slate-200 text-slate-400'}`}>
                           <span className="material-symbols-outlined text-[32px] opacity-20">inventory_2</span>
                           <p className="text-[10px] font-black uppercase tracking-widest">No Historical Record</p>
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>

          <div className="space-y-6">
            <div className="flex justify-between items-center px-1">
              <h3
                className={`text-xl font-bold flex items-center gap-2 ${isDarkMode ? "text-white" : "text-gray-900"
                  }`}
              >
                Completed Scans & History
              </h3>
              <span className="bg-[#007aff]/10 text-[#007aff] px-3 py-1 rounded-full text-xs font-bold border border-[#007aff]/20">
                {sortedReports.length} Cases Total
              </span>
            </div>

            {sortedReports.map((scan) => {
              const cnnLabel = (scan.cnn_top5?.[0]?.label || scan.prediction || "").toLowerCase();
              const svmLabel = (scan.svm_top5?.[0]?.label || scan.svm_prediction || scan.prediction || "").toLowerCase();
              
              // Clinical Rule: Truly healthy ONLY if both models agree on normalcy
              const cnnIsHealthy = cnnLabel.includes("normal") || cnnLabel.includes("healthy");
              const svmIsHealthy = svmLabel.includes("normal") || svmLabel.includes("healthy");
              const isTrulyHealthy = cnnIsHealthy && svmIsHealthy;

              const reportDate = scan.createdAt?.toDate
                ? scan.createdAt.toDate()
                : new Date(scan.createdAt || 0);

              const dateStr = reportDate.toLocaleDateString("en-US", {
                year: "numeric",
                month: "short",
                day: "numeric",
              });

              const timeStr = reportDate.toLocaleTimeString("en-US", {
                hour: "2-digit",
                minute: "2-digit",
              });

              return (
                <div
                  key={scan.id}
                  className={`border rounded-xl p-6 flex flex-col lg:flex-row gap-8 shadow-sm transition-colors ${isDarkMode
                    ? "bg-[#111a22] border-[#233648] hover:border-[#334b61]"
                    : "bg-white border-gray-200 hover:border-gray-300"
                    }`}
                >
                  <div className="shrink-0 relative group">
                    <img
                      src={scan.imageUrl}
                      className={`w-full lg:w-[320px] h-56 object-cover rounded-lg border bg-black ${isDarkMode ? "border-[#233648]" : "border-gray-200"
                        }`}
                      alt="scan"
                    />
                    <div className="absolute inset-x-0 bottom-0 p-3 bg-gradient-to-t from-black/80 to-transparent rounded-b-lg">
                      <p className="text-xs text-gray-400 text-center">Fundus Image</p>
                    </div>
                  </div>

                  <div className="flex-1 flex flex-col justify-between">
                    <div className="flex justify-between items-start mb-6">
                      <div>
                        <h4
                          className={`font-bold text-lg mb-1 ${isDarkMode ? "text-white" : "text-gray-900"
                            }`}
                        >
                          Retinal Fundus Photography - {scan.eye || "Unknown Eye"}
                        </h4>
                        <p
                          className={`text-xs font-medium flex items-center gap-1 ${isDarkMode ? "text-muted-dark" : "text-gray-500"
                            }`}
                        >
                          Scanned on {dateStr}
                          <span className="w-1 h-1 rounded-full bg-gray-600 mx-1"></span>
                          {timeStr}
                        </p>
                      </div>

                      <span
                        className={`px-4 py-2 rounded-xl text-[10px] font-black tracking-[0.2em] uppercase border transition-all duration-300 ${isTrulyHealthy
                          ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20 shadow-[0_0_20px_-5px] shadow-emerald-500/20"
                          : "bg-rose-500/10 text-rose-400 border-rose-500/20 animate-pulse shadow-[0_0_20px_-5px] shadow-rose-500/20"
                          }`}
                      >
                        {isTrulyHealthy ? "Optimal Health Detected" : "High Risk Signature"}
                      </span>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                      <div
                        className={`p-5 rounded-xl border ${isDarkMode
                          ? "bg-[#1c2a38]/50 border-[#233648]"
                          : "bg-gray-50 border-gray-200"
                          }`}
                      >
                        <p className="text-[#007aff] text-[10px] uppercase font-bold tracking-wider mb-4">
                          AI Prediction Results
                        </p>
                        <div className="space-y-4">
                          {/* CNN MODEL PREDICTION */}
                          <div>
                            <div className="flex justify-between text-xs mb-1.5">
                              <span className={isDarkMode ? "text-gray-300" : "text-gray-600"}>
                                CNN Model: {scan.cnn_top5?.[0]?.label || finalLabel}
                              </span>
                              <span className={`font-bold ${cnnIsHealthy ? "text-emerald-400" : "text-rose-400"}`}>
                                {Math.round((scan.cnn_top5?.[0]?.confidence || scan.confidence || 0.80) * 100)}%
                              </span>
                            </div>
                            <div className={`h-1.5 rounded-full overflow-hidden ${isDarkMode ? "bg-[#111a22]" : "bg-gray-200"}`}>
                              <div
                                className={`h-full rounded-full transition-all duration-500 ${cnnIsHealthy ? "bg-emerald-500" : "bg-rose-500"}`}
                                style={{ width: `${(scan.cnn_top5?.[0]?.confidence || scan.confidence || 0.80) * 100}%` }}
                              />
                            </div>
                          </div>

                          {/* SVM MODEL PREDICTION */}
                          <div>
                            <div className="flex justify-between text-xs mb-1.5">
                              <span className={isDarkMode ? "text-gray-300" : "text-gray-600"}>
                                SVM Model: {scan.svm_top5?.[0]?.label || scan.svm_prediction || finalLabel}
                              </span>
                              <span className={`font-bold ${svmIsHealthy ? "text-emerald-400" : "text-rose-400"}`}>
                                {Math.round((scan.svm_top5?.[0]?.confidence || scan.svm_confidence || scan.confidence || 0.82) * 100)}%
                              </span>
                            </div>
                            <div className={`h-1.5 rounded-full overflow-hidden ${isDarkMode ? "bg-[#111a22]" : "bg-gray-200"}`}>
                              <div
                                  className={`h-full rounded-full transition-all duration-500 ${svmIsHealthy ? "bg-emerald-500" : "bg-rose-500"}`}
                                  style={{ width: `${(scan.svm_top5?.[0]?.confidence || scan.svm_confidence || scan.confidence || 0.82) * 100}%` }}
                              />
                            </div>
                          </div>
                        </div>
                      </div>

                      <div
                        className={`p-5 rounded-xl border flex flex-col ${isDarkMode
                          ? "bg-[#1c2a38]/50 border-[#233648]"
                          : "bg-gray-50 border-gray-200"
                          }`}
                      >
                        <p className={`text-[10px] font-bold uppercase tracking-wider mb-3 ${isDarkMode ? "text-muted-dark" : "text-gray-500"}`}>
                          Doctor’s Feedback
                        </p>
                        <div className="flex-1 text-sm italic leading-relaxed">
                          "{scan.doctorNotes || "No clinical notes recorded."}"
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </main>
      </div>
    </div>
  );
}
